apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  config.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki.kube-prometheus-stack.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: apache-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: wordpress
              app: wordpress
              __path__: /var/log/apache2/*.log