auth:
  existingSecret: mysql-credentials
  secretKeys:
    adminPassword: mysql-root-password
    userPassword: mysql-password
  database: "wordpress"
  username: "wpuser"

architecture: replication

primary:
  persistence:
    enabled: true
    size: 8Gi

secondary:
  replicaCount: 2
  persistence:
    enabled: true
    size: 8Gi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: kube-prometheus-stack