name: Setup Observability

on:
  push:
    branches:
      - main
  workflow_dispatch: # This is the line that enables manual runs

permissions:
  id-token: write
  contents: read

jobs:
  run-setup-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-southeast-1

      - name: Make script executable
        run: chmod +x ./setup-observability.sh

      - name: Run observability setup script
        run: ./setup-observability.sh
